spark.master                     spark://spark-master:7077
spark.driver.memory              1g
spark.executor.memory            1g
spark.executor.instances         1
spark.sql.catalogImplementation  hive
spark.hadoop.hive.metastore.uris thrift://hive-metastore:9083
spark.sql.warehouse.dir          hdfs://namenode:9000/user/hive/warehouse
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.sql.extensions             org.apache.spark.sql.hudi.HoodieSparkSessionExtension
spark.sql.catalog.spark_catalog  org.apache.spark.sql.hudi.catalog.HoodieCatalog